### ISSUE TITLE
Color picker not showing up

### ISSUE THREAD

**Issue by rsxyo** [Litteeen/Melody#1]
It was working the first time I downloaded, then I uninstalled and installed back again after a while and nothing… All the dependencies are install and I also have cleaned the preferences files through iCleaner and still not appearing. 

![48BF7434-FD3C-4C62-A70C-41CF745A9CA6](https://user-images.githubusercontent.com/59376576/72672601-350e1280-3a54-11ea-98f0-124f2f83bf46.png)

**Comment by Litteeen** [comment]
Try to disable other tweaks, sometimes the sparkcolorpicker is a little buggy
