### ISSUE TITLE
UIButtonLabels 

### ISSUE THREAD

**Issue by SavvasT01** [Litteeen/Melody#2]
UIButtonLabels won’t theme inside settings application. Running iOS 13.3 on iPhone 6s.
![0AEA5C93-0573-4DF0-85F9-3DE038BB5575](https://user-images.githubusercontent.com/60052284/72673229-ac996d00-3a67-11ea-9e53-d4d3139294c1.png)

**Comment by Litteeen** [comment]
It looks like you have some tweak like BetterSettings installed right?

**Comment by SavvasT01** [comment]
I’m only using noctisneo and shuffle..

**Comment by Litteeen** [comment]
Can you try to disable noctis with icleaner?

**Comment by SavvasT01** [comment]
That fixed it... will there be a fix so I don’t need to disable noctis?

**Comment by Litteeen** [comment]
Noctis may overrides melody’s settings so i guess no way around
